
name: telefaune
description: A Flutter Web project with Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.0.0
  image_picker: ^1.0.4
  firebase_storage: ^11.0.0
  geolocator: ^10.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/gecko_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/gecko_logo.png
  