name: telefaune
description: Une application de suivi d'observations naturalistes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Fonctionnalités
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.0
  image_picker: ^1.0.4

  # Web interop
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/gecko_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/gecko_logo.png
